name: isoko_scooter
description: A scooter rental mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  go_router: ^13.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
